name: Daily Anime Adventures Value Scrape

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9:00 AM UTC daily
  workflow_dispatch:      # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Use browser-actions/setup-chrome instead of manual installation
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      # Use nanasess/setup-chromedriver instead of manual installation
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 selenium pandas openpyxl xlsxwriter

      # Verify Chrome and ChromeDriver installations
      - name: Check versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run scraper
        run: python anime_adventures_excel_report.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Anime_Adventures_Value_List*.xlsx
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily update: $(date +'%Y-%m-%d')"
            git push
          fi